# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 52) do

  create_table "activity_categories", :force => true do |t|
    t.column "name", :string
  end

  create_table "activity_logs", :force => true do |t|
    t.column "activity_category_id", :string
    t.column "user_id",              :string,   :limit => 36
    t.column "profile_id",           :string,   :limit => 36
    t.column "description",          :string
    t.column "session_id",           :string
    t.column "ip_address",           :string
    t.column "created_at",           :datetime
  end

  add_index "activity_logs", ["activity_category_id"], :name => "activity_category_id"

  create_table "ad_clicks", :force => true do |t|
    t.column "ad_id",      :string,   :limit => 36, :null => false
    t.column "user_id",    :string,   :limit => 36
    t.column "profile_id", :string,   :limit => 36
    t.column "created_at", :datetime,               :null => false
  end

  add_index "ad_clicks", ["ad_id"], :name => "ad_id"

  create_table "ad_views", :force => true do |t|
    t.column "ad_id",      :string,   :limit => 36, :null => false
    t.column "user_id",    :string,   :limit => 36
    t.column "profile_id", :string,   :limit => 36
    t.column "created_at", :datetime,               :null => false
  end

  add_index "ad_views", ["ad_id"], :name => "ad_id"

  create_table "ads", :force => true do |t|
    t.column "name",        :string,   :null => false
    t.column "height",      :integer,  :null => false
    t.column "width",       :integer,  :null => false
    t.column "image_path",  :string,   :null => false
    t.column "link",        :string,   :null => false
    t.column "target_page", :string
    t.column "created_at",  :datetime, :null => false
    t.column "deleted_at",  :datetime
  end

  add_index "ads", ["name"], :name => "index_ads_on_name"
  add_index "ads", ["target_page"], :name => "index_ads_on_target_page"

  create_table "digest_histories", :force => true do |t|
    t.column "user_id",           :string,   :limit => 36, :null => false
    t.column "digest_sent_flag",  :string,   :limit => 1,  :null => false
    t.column "last_process_date", :datetime,               :null => false
  end

  add_index "digest_histories", ["user_id"], :name => "user_id"

  create_table "featured_profiles", :force => true do |t|
    t.column "profile_type", :string
    t.column "profile_id",   :string,   :limit => 36
    t.column "created_at",   :datetime,               :null => false
  end

  add_index "featured_profiles", ["profile_id"], :name => "profile_id"

  create_table "feedbacks", :force => true do |t|
    t.column "user_id",    :string,   :limit => 36
    t.column "first_name", :string
    t.column "last_name",  :string
    t.column "email",      :string
    t.column "ip_address", :string
    t.column "comments",   :text
    t.column "cgi_env",    :text
    t.column "created_at", :datetime
  end

  add_index "feedbacks", ["user_id"], :name => "user_id"

  create_table "invitations", :force => true do |t|
    t.column "user_id",            :string,   :limit => 36, :null => false
    t.column "to_email",           :string,                 :null => false
    t.column "to_first_name",      :string
    t.column "to_last_name",       :string
    t.column "invitation_message", :text,                   :null => false
    t.column "created_at",         :datetime,               :null => false
    t.column "accepted_at",        :datetime
  end

  add_index "invitations", ["user_id"], :name => "user_id"

  create_table "latlongs", :force => true do |t|
    t.column "seq",     :integer, :null => false
    t.column "lat",     :float,   :null => false
    t.column "lng",     :float,   :null => false
    t.column "zcta_id", :integer, :null => false
  end

  add_index "latlongs", ["zcta_id"], :name => "zcta_id"

  create_table "profile_favorites", :force => true do |t|
    t.column "profile_id",        :string,   :limit => 36, :null => false
    t.column "target_profile_id", :string,   :limit => 36, :null => false
    t.column "created_at",        :datetime
    t.column "deleted_at",        :datetime
  end

  add_index "profile_favorites", ["profile_id"], :name => "profile_id"
  add_index "profile_favorites", ["target_profile_id"], :name => "target_profile_id"

  create_table "profile_field_engine_indices", :force => true do |t|
    t.column "profile_id",               :string,  :limit => 36,                    :null => false
    t.column "is_owner",                 :boolean,                                  :null => false
    t.column "zip_code",                 :string,                                   :null => false
    t.column "property_type",            :string,                                   :null => false
    t.column "beds",                     :integer,                                  :null => false
    t.column "baths",                    :integer,                                  :null => false
    t.column "square_feet",              :integer,                                  :null => false
    t.column "square_feet_min",          :integer,                                  :null => false
    t.column "square_feet_max",          :integer,                                  :null => false
    t.column "price",                    :integer
    t.column "price_min",                :integer
    t.column "price_max",                :integer
    t.column "units",                    :integer,                                  :null => false
    t.column "units_min",                :integer,                                  :null => false
    t.column "units_max",                :integer,                                  :null => false
    t.column "acres",                    :integer,                                  :null => false
    t.column "acres_min",                :integer,                                  :null => false
    t.column "acres_max",                :integer,                                  :null => false
    t.column "privacy",                  :string
    t.column "property_type_sort_order", :integer
    t.column "has_profile_image",        :boolean,               :default => false, :null => false
  end

  add_index "profile_field_engine_indices", ["profile_id"], :name => "index_profile_field_engine_indices_on_profile_id"
  add_index "profile_field_engine_indices", ["zip_code"], :name => "index_profile_field_engine_indices_on_zip_code"

  create_table "profile_fields", :force => true do |t|
    t.column "profile_id", :string,   :limit => 36, :null => false
    t.column "key",        :string,                 :null => false
    t.column "value",      :string
    t.column "value_text", :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "deleted_at", :datetime
  end

  add_index "profile_fields", ["profile_id"], :name => "profile_id"
  add_index "profile_fields", ["key"], :name => "index_profile_fields_on_key"
  add_index "profile_fields", ["value"], :name => "index_profile_fields_on_value"

  create_table "profile_images", :force => true do |t|
    t.column "profile_id",   :string,   :limit => 36, :null => false
    t.column "created_at",   :datetime
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "parent_id",    :string,   :limit => 36
    t.column "thumbnail",    :string
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "deleted_at",   :datetime
  end

  add_index "profile_images", ["profile_id"], :name => "profile_id"

  create_table "profile_message_recipients", :force => true do |t|
    t.column "from_profile_id",    :string,   :limit => 36, :null => false
    t.column "to_profile_id",      :string,   :limit => 36, :null => false
    t.column "viewed_at",          :datetime
    t.column "profile_message_id", :string,   :limit => 36, :null => false
    t.column "deleted_at",         :datetime
  end

  add_index "profile_message_recipients", ["from_profile_id"], :name => "from_profile_id"
  add_index "profile_message_recipients", ["to_profile_id"], :name => "to_profile_id"
  add_index "profile_message_recipients", ["profile_message_id"], :name => "profile_message_id"

  create_table "profile_messages", :force => true do |t|
    t.column "body",                        :text
    t.column "created_at",                  :datetime
    t.column "subject",                     :string
    t.column "reply_to_profile_message_id", :string,   :limit => 36
  end

  add_index "profile_messages", ["reply_to_profile_message_id"], :name => "reply_to_profile_message_id"

  create_table "profile_types", :force => true do |t|
    t.column "name",      :string
    t.column "permalink", :string
  end

  add_index "profile_types", ["permalink"], :name => "index_profile_types_on_permalink", :unique => true

  create_table "profile_views", :force => true do |t|
    t.column "profile_id",           :string,   :limit => 36, :null => false
    t.column "viewed_by_profile_id", :string,   :limit => 36, :null => false
    t.column "created_at",           :datetime
    t.column "deleted_at",           :datetime
  end

  add_index "profile_views", ["profile_id"], :name => "profile_id"
  add_index "profile_views", ["viewed_by_profile_id"], :name => "viewed_by_profile_id"

  create_table "profiles", :force => true do |t|
    t.column "profile_type_id", :string,   :limit => 36, :null => false
    t.column "user_id",         :string,   :limit => 36
    t.column "name",            :string,                 :null => false
    t.column "permalink",       :string,                 :null => false
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "deleted_at",      :datetime
    t.column "delete_reason",   :text
  end

  add_index "profiles", ["permalink"], :name => "index_profiles_on_permalink", :unique => true
  add_index "profiles", ["profile_type_id"], :name => "index_profiles_on_profile_type_id"
  add_index "profiles", ["user_id"], :name => "index_profiles_on_user_id"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "site_stat_types", :force => true do |t|
    t.column "name",       :string,   :null => false
    t.column "created_at", :datetime, :null => false
  end

  create_table "site_stats", :force => true do |t|
    t.column "site_stat_type_id", :string,  :limit => 36
    t.column "user_id",           :string,  :limit => 36
    t.column "profile_id",        :string,  :limit => 36
    t.column "value_num",         :integer
    t.column "stats_date",        :date,                  :null => false
    t.column "created_on",        :date,                  :null => false
  end

  add_index "site_stats", ["site_stat_type_id"], :name => "site_stat_type_id"

  create_table "tips", :force => true do |t|
    t.column "tip_text",    :string
    t.column "target_page", :string
    t.column "created_at",  :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "first_name",                :string
    t.column "last_name",                 :string
    t.column "home_phone",                :string
    t.column "business_phone",            :string
    t.column "mobile_phone",              :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "last_login_at",             :datetime
    t.column "previous_login_at",         :datetime
    t.column "security_token",            :string,   :limit => 40
    t.column "security_token_expiry",     :datetime
    t.column "digest_frequency",          :string,   :limit => 1,  :default => "D"
    t.column "admin_flag",                :boolean,                :default => false, :null => false
  end

  add_index "users", ["login"], :name => "index_users_on_login", :unique => true

  create_table "zctas", :force => true do |t|
    t.column "zcta",   :integer, :null => false
    t.column "zip_id", :integer, :null => false
    t.column "points", :text
    t.column "levels", :text
  end

  add_index "zctas", ["zip_id"], :name => "zip_id"

  create_table "zips", :force => true do |t|
    t.column "zip",   :string, :limit => 5, :null => false
    t.column "state", :string
    t.column "city",  :string
    t.column "lat",   :float
    t.column "lng",   :float
  end

  add_index "zips", ["zip"], :name => "index_zips_on_zip"

  add_foreign_key "activity_logs", ["activity_category_id"], "activity_categories", ["id"], :name => "activity_logs_ibfk_1"

  add_foreign_key "ad_clicks", ["ad_id"], "ads", ["id"], :name => "ad_clicks_ibfk_1"

  add_foreign_key "ad_views", ["ad_id"], "ads", ["id"], :name => "ad_views_ibfk_1"

  add_foreign_key "digest_histories", ["user_id"], "users", ["id"], :name => "digest_histories_ibfk_1"

  add_foreign_key "featured_profiles", ["profile_id"], "profiles", ["id"], :name => "featured_profiles_ibfk_1"

  add_foreign_key "feedbacks", ["user_id"], "users", ["id"], :name => "feedbacks_ibfk_1"

  add_foreign_key "invitations", ["user_id"], "users", ["id"], :name => "invitations_ibfk_1"

  add_foreign_key "profile_favorites", ["profile_id"], "profiles", ["id"], :name => "profile_favorites_ibfk_1"
  add_foreign_key "profile_favorites", ["target_profile_id"], "profiles", ["id"], :name => "profile_favorites_ibfk_2"

  add_foreign_key "profile_fields", ["profile_id"], "profiles", ["id"], :name => "profile_fields_ibfk_1"

  add_foreign_key "profile_images", ["profile_id"], "profiles", ["id"], :name => "profile_images_ibfk_1"

  add_foreign_key "profile_message_recipients", ["from_profile_id"], "profiles", ["id"], :name => "profile_message_recipients_ibfk_1"
  add_foreign_key "profile_message_recipients", ["to_profile_id"], "profiles", ["id"], :name => "profile_message_recipients_ibfk_2"
  add_foreign_key "profile_message_recipients", ["profile_message_id"], "profile_messages", ["id"], :name => "profile_message_recipients_ibfk_3"

  add_foreign_key "profile_messages", ["reply_to_profile_message_id"], "profile_messages", ["id"], :name => "profile_messages_ibfk_1"

  add_foreign_key "profile_views", ["profile_id"], "profiles", ["id"], :name => "profile_views_ibfk_1"
  add_foreign_key "profile_views", ["viewed_by_profile_id"], "profiles", ["id"], :name => "profile_views_ibfk_2"

  add_foreign_key "profiles", ["profile_type_id"], "profile_types", ["id"], :name => "profiles_ibfk_1"
  add_foreign_key "profiles", ["user_id"], "users", ["id"], :name => "profiles_ibfk_2"

  add_foreign_key "site_stats", ["site_stat_type_id"], "site_stat_types", ["id"], :name => "site_stats_ibfk_1"

end
